import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';
import { formatNaira, amountInWords, getCurrentNigeriaDateTime } from './formatters';
import { PaymentTransaction, SchoolSettings, Student } from '../types';

export interface ReportPdfOptions {
  title: string;
  subtitle?: string;
  session: string;
  term: string;
  generatedBy: string;
  headers: string[];
  rows: (string | number)[][];
  summaryStats?: { label: string; value: string }[];
  schoolSettings: SchoolSettings;
  orientation?: 'portrait' | 'landscape';
}

export const generateReportPDF = (options: ReportPdfOptions) => {
  const {
    title,
    subtitle,
    session,
    term,
    generatedBy,
    headers,
    rows,
    summaryStats,
    schoolSettings,
    orientation = 'portrait',
  } = options;

  const doc = new jsPDF({
    orientation,
    unit: 'mm',
    format: 'a4',
  });

  const { full: generatedTimestamp } = getCurrentNigeriaDateTime();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Primary Header Banner
  doc.setFillColor(6, 78, 59); // Deep Emerald #064e3b
  doc.rect(0, 0, pageWidth, 28, 'F');

  // Gold accent line
  doc.setFillColor(217, 119, 6); // Amber/Gold #d97706
  doc.rect(0, 28, pageWidth, 2, 'F');

  // School Header
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.text(schoolSettings.schoolName.toUpperCase(), pageWidth / 2, 11, { align: 'center' });

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(220, 252, 231); // light emerald
  doc.text(schoolSettings.schoolMotto || 'Excellence in Knowledge & Character', pageWidth / 2, 17, { align: 'center' });
  doc.text(`${schoolSettings.address} | Tel: ${schoolSettings.phone} | Email: ${schoolSettings.email}`, pageWidth / 2, 23, { align: 'center' });

  // Report Title & Metadata Box
  doc.setTextColor(30, 41, 59);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text(title.toUpperCase(), 14, 38);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(71, 85, 105);

  let metaY = 44;
  if (subtitle) {
    doc.text(subtitle, 14, metaY);
    metaY += 5;
  }

  doc.text(`Academic Session: ${session}   |   Term: ${term}`, 14, metaY);
  metaY += 5;
  doc.text(`Generated By: ${generatedBy}   |   Date & Time: ${generatedTimestamp}`, 14, metaY);
  metaY += 4;

  // Summary statistics badges if any
  if (summaryStats && summaryStats.length > 0) {
    metaY += 2;
    const statBoxWidth = (pageWidth - 28 - (summaryStats.length - 1) * 4) / summaryStats.length;
    summaryStats.forEach((stat, i) => {
      const boxX = 14 + i * (statBoxWidth + 4);
      doc.setFillColor(241, 245, 249);
      doc.roundedRect(boxX, metaY, statBoxWidth, 12, 1.5, 1.5, 'F');
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7.5);
      doc.setTextColor(100, 116, 139);
      doc.text(stat.label.toUpperCase(), boxX + statBoxWidth / 2, metaY + 4.5, { align: 'center' });
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9.5);
      doc.setTextColor(15, 23, 42);
      doc.text(stat.value, boxX + statBoxWidth / 2, metaY + 9.5, { align: 'center' });
    });
    metaY += 16;
  } else {
    metaY += 4;
  }

  // AutoTable
  autoTable(doc, {
    startY: metaY,
    head: [headers],
    body: rows,
    theme: 'grid',
    headStyles: {
      fillColor: [6, 78, 59],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 8.5,
      halign: 'left',
    },
    styles: {
      fontSize: 8,
      cellPadding: 2.2,
      textColor: [30, 41, 59],
      overflow: 'linebreak',
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
    margin: { left: 14, right: 14, bottom: 18 },
    didDrawPage: (data) => {
      // Page footer
      const str = `Page ${data.pageNumber} of ${(doc as any).internal.getNumberOfPages()}`;
      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184);
      doc.text(str, pageWidth / 2, doc.internal.pageSize.getHeight() - 8, { align: 'center' });
      doc.text(`FLO Famous School Management System — Confidential Financial Document`, 14, doc.internal.pageSize.getHeight() - 8);
    },
  });

  const fileName = `${title.toLowerCase().replace(/\s+/g, '_')}_${Date.now()}.pdf`;
  doc.save(fileName);
};

export const generateReceiptPDF = (
  payment: PaymentTransaction,
  student: Student | undefined,
  schoolSettings: SchoolSettings
) => {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a5', // A5 is the standard professional receipt size for Nigerian schools
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // Outer decorative border
  doc.setDrawColor(6, 78, 59);
  doc.setLineWidth(0.8);
  doc.rect(7, 7, pageWidth - 14, pageHeight - 14);

  doc.setDrawColor(217, 119, 6);
  doc.setLineWidth(0.3);
  doc.rect(8.5, 8.5, pageWidth - 17, pageHeight - 17);

  // Top header banner
  doc.setFillColor(6, 78, 59);
  doc.rect(9, 9, pageWidth - 18, 24, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(13);
  doc.text(schoolSettings.schoolName.toUpperCase(), pageWidth / 2, 16, { align: 'center' });

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(220, 252, 231);
  doc.text(schoolSettings.schoolMotto || 'Knowledge, Discipline and Excellence', pageWidth / 2, 21, { align: 'center' });
  doc.text(`${schoolSettings.address} | Tel: ${schoolSettings.phone}`, pageWidth / 2, 26, { align: 'center' });
  doc.text(`Email: ${schoolSettings.email} | Web: ${schoolSettings.website}`, pageWidth / 2, 30, { align: 'center' });

  // Receipt Ribbon
  doc.setFillColor(217, 119, 6);
  doc.rect(9, 33, pageWidth - 18, 7, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(9.5);
  doc.text('OFFICIAL FEE PAYMENT RECEIPT', pageWidth / 2, 38, { align: 'center' });

  // Receipt No & Date row
  doc.setTextColor(30, 41, 59);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8.5);
  doc.text(`Receipt No: ${payment.receiptNumber}`, 12, 46);
  doc.setFont('helvetica', 'normal');
  doc.text(`Date: ${payment.paymentDate}  |  Time: ${payment.paymentTime}`, pageWidth - 12, 46, { align: 'right' });

  // Student details panel
  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(12, 50, pageWidth - 24, 28, 2, 2, 'FD');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(71, 85, 105);
  doc.text('STUDENT INFORMATION', 15, 55);

  doc.setFont('helvetica', 'normal');
  doc.setTextColor(30, 41, 59);
  doc.setFontSize(8.5);
  doc.text(`Student Name: `, 15, 61);
  doc.setFont('helvetica', 'bold');
  doc.text(payment.studentName, 38, 61);

  doc.setFont('helvetica', 'normal');
  doc.text(`Student ID: `, 15, 67);
  doc.setFont('helvetica', 'bold');
  doc.text(payment.studentId, 38, 67);

  doc.setFont('helvetica', 'normal');
  doc.text(`Class: `, 15, 73);
  doc.setFont('helvetica', 'bold');
  doc.text(`${payment.className} (${payment.academicSession} - ${payment.term})`, 38, 73);

  if (student?.parentName) {
    doc.setFont('helvetica', 'normal');
    doc.text(`Parent/Guardian: ${student.parentName} (${student.parentPhone})`, pageWidth - 15, 61, { align: 'right' });
  }

  // Payment Breakdown Table
  autoTable(doc, {
    startY: 81,
    margin: { left: 12, right: 12 },
    head: [['Fee Item / Category', 'Payment Method', 'Transaction Ref', 'Amount (NGN)']],
    body: [
      [
        payment.feeCategory,
        payment.paymentMethod,
        payment.transactionReference || 'N/A',
        formatNaira(payment.amount),
      ],
    ],
    theme: 'grid',
    headStyles: {
      fillColor: [6, 78, 59],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 8,
    },
    styles: {
      fontSize: 8,
      cellPadding: 3,
      textColor: [15, 23, 42],
    },
  });

  const finalY = (doc as any).lastAutoTable.finalY + 4;

  // Words & Balance summary
  doc.setFillColor(241, 245, 249);
  doc.roundedRect(12, finalY, pageWidth - 24, 30, 1.5, 1.5, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7.5);
  doc.setTextColor(71, 85, 105);
  doc.text('AMOUNT IN WORDS:', 15, finalY + 5);

  doc.setFont('helvetica', 'italic');
  doc.setTextColor(6, 78, 59);
  doc.setFontSize(8.5);
  doc.text(amountInWords(payment.amount), 15, finalY + 10);

  // Balances
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(71, 85, 105);
  doc.setFontSize(8);
  doc.text(`Previous Balance:`, 15, finalY + 17);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 41, 59);
  doc.text(formatNaira(payment.previousBalance), 45, finalY + 17);

  doc.setFont('helvetica', 'normal');
  doc.setTextColor(71, 85, 105);
  doc.text(`Amount Paid:`, 15, finalY + 22);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(16, 185, 129); // emerald green
  doc.text(formatNaira(payment.amount), 45, finalY + 22);

  doc.setFont('helvetica', 'normal');
  doc.setTextColor(71, 85, 105);
  doc.text(`Remaining Balance:`, 15, finalY + 27);
  doc.setFont('helvetica', 'bold');
  const isOverpaid = payment.newBalance < 0;
  doc.setTextColor(isOverpaid ? 37 : payment.newBalance > 0 ? 220 : 16, isOverpaid ? 99 : payment.newBalance > 0 ? 38 : 185, isOverpaid ? 235 : payment.newBalance > 0 ? 38 : 129);
  doc.text(isOverpaid ? `${formatNaira(Math.abs(payment.newBalance))} (CREDIT)` : formatNaira(payment.newBalance), 45, finalY + 27);

  // Status stamp
  if (payment.status === 'VOIDED') {
    doc.setTextColor(239, 68, 68);
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('*** VOIDED TRANSACTION ***', pageWidth / 2, finalY + 20, { align: 'center' });
    doc.setFontSize(7.5);
    doc.text(`Reason: ${payment.voidReason || 'Admin reversal'}`, pageWidth / 2, finalY + 25, { align: 'center' });
  }

  // Signature and Cashier info
  const sigY = finalY + 36;
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(71, 85, 105);
  doc.setFontSize(7.5);
  doc.text(`Recorded By: ${payment.recordedBy}`, 15, sigY);
  doc.text(`Cashier / Bursar Stamp & Signature:`, pageWidth - 65, sigY);

  doc.setDrawColor(148, 163, 184);
  doc.line(pageWidth - 65, sigY + 12, pageWidth - 15, sigY + 12);
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(7);
  doc.text('Authorized School Signature', pageWidth - 40, sigY + 16, { align: 'center' });

  // Footnote
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(6.5);
  doc.setTextColor(148, 163, 184);
  doc.text(
    'Fees paid are non-refundable. Please keep this receipt safe as proof of fee payment.',
    pageWidth / 2,
    pageHeight - 11,
    { align: 'center' }
  );

  doc.save(`${payment.receiptNumber}.pdf`);
};

export const exportToExcel = (fileName: string, sheetName: string, data: any[]) => {
  const worksheet = XLSX.utils.json_to_sheet(data);
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, sheetName);
  XLSX.writeFile(workbook, `${fileName}_${Date.now()}.xlsx`);
};

export const exportToCSV = (fileName: string, data: any[]) => {
  const worksheet = XLSX.utils.json_to_sheet(data);
  const csvOutput = XLSX.utils.sheet_to_csv(worksheet);
  const blob = new Blob([csvOutput], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  link.href = URL.createObjectURL(blob);
  link.setAttribute('download', `${fileName}_${Date.now()}.csv`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};

export const downloadStudentImportTemplate = () => {
  const sampleData = [
    {
      'Student ID': 'FLO-2026-0030',
      'First Name': 'Emeka',
      'Middle Name': 'Chukwu',
      'Last Name': 'Okafor',
      Gender: 'Male',
      'Date of Birth': '2014-05-12',
      'Parent Name': 'Mr. Anthony Okafor',
      'Parent Phone': '08031234567',
      'Parent Email': 'anthony.okafor@gmail.com',
      Address: 'Plot 12 Independence Layout, Enugu',
      Section: 'PRIMARY',
      Class: 'Primary 5',
      'Academic Session': '2026/2027',
      'Admission Date': '2026-09-01',
      'Previous School': 'St. Jude Model School',
      Notes: 'Prefers front row seating',
    },
    {
      'Student ID': 'FLO-2026-0031',
      'First Name': 'Amina',
      'Middle Name': 'Zainab',
      'Last Name': 'Bello',
      Gender: 'Female',
      'Date of Birth': '2012-08-20',
      'Parent Name': 'Alhaji Umar Bello',
      'Parent Phone': '08029876543',
      'Parent Email': 'umar.bello@yahoo.com',
      Address: '15 Okigwe Road, Owerri',
      Section: 'JUNIOR_SECONDARY',
      Class: 'JSS 1',
      'Academic Session': '2026/2027',
      'Admission Date': '2026-09-01',
      'Previous School': 'Federal Staff Primary School',
      Notes: 'Transfer student from Abuja',
    },
  ];

  exportToExcel('FLO_Famous_Students_Import_Template', 'StudentsTemplate', sampleData);
};
